### ISSUE TITLE
Message-type IUs sent from ipaaca-java have EventType "ADDED" in event handlers

### ISSUE THREAD

**Issue by hbuschme** [SocialCognitiveSystems/ipaaca#3]
Message-type IUs in ipaaca-java do not seem to differ from normal IUs in terms of the EventType that is provided to handlers. This can for example be seen in the ipaaca-iu-sniffer which lists Message-type IUs sent from ipaaca-java as "ADDED".

**Comment by ryaghoub** [comment]
New version pushed to scssrc master; KOMPASS demo works well.  Currently no time to write Message test - please test your use case and forward the push / complain here depending on results :)

**Comment by ryaghoub** [comment]
Wrote a test program now. As far as I can see everything seems to work now; pushed.
